language: rust
cache:
  cargo: true
  directories:
    - book/highlight.js/node_modules
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
  - ci/install-mdbook
  - ci/build-highlight-js
  - cargo build --verbose # https://docs.travis-ci.com/user/languages/rust/#Dependency-Management

script:
  - cargo build --verbose --all # https://docs.travis-ci.com/user/languages/rust/#Default-Build-Script
  - cargo test --verbose --all # https://docs.travis-ci.com/user/languages/rust/#Default-Build-Script
  - ci/build-book

deploy:
  # Deploy the book to Github Pages
  # https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: book/build
    on:
      branch: master
      rust: stable

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/54d1cf84e3e6d80f3faa
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
